module.exports = {
    MACAROON_ACCEPTED: 'MACAROON_ACCEPTED',
    MACAROON_REFUSED: 'MACAROON_REFUSED',
    MACAROON_SENT: 'MACAROON_SENT',
    SUGGESTION_SKIPPED: 'SUGGESTION_SKIPPED',
    REFRESH_SUGGESTIONS: 'REFRESH_SUGGESTIONS'
};
