module.exports = {
    MACAROON_ACCEPTED: 'MACAROON_ACCEPTED',
    MACAROON_REFUSED: 'MACAROON_REFUSED',
    MACAROON_SENT: 'MACAROON_SENT',
    MESSAGE_SENT: 'MESSAGE_SENT',
    SUGGESTION_SKIPPED: 'SUGGESTION_SKIPPED',
    SELECTION_PICKED: 'SELECTION_PICKED',
    REFRESH_SUGGESTIONS: 'REFRESH_SUGGESTIONS',
    GAMING_GAME_SENT: 'GAMING_GAME_SENT',
    GAMING_GAME_ANSWERED: 'GAMING_GAME_ANSWERED',
};
